### PR TITLE
Update links to supported Bats modules

### PR DESCRIPTION
**Pull request by hyperupcall**
Modules such as `bats-support`, `bats-file`, and `bats-assert` are now the most update to date within the `bats-core` organization. This PR updates those links as such

### CODE REVIEW

**Comment by jetmartin** [comment]
Hi,
Thank's seems a good update, I'll gonna check that later on.
Best

**Comment by jetmartin** [comment]
Hi,
Thank for the links to the new up to date repos.

Quick question as I look at your updates, I wondering if we better should display the badges or use specific ones to display :
 * The latest version (as of today)
 * The minimal version (as in another PR you added v1.5.0 features support)
 * The latest tested version (witch require time to be updated that I clearly don't have, and I see no interest to push a new release for that)

Ex. : [https://img.shields.io/badge/bats--core-%3E%3D1.5.0-green](https://img.shields.io/badge/bats--core-%3E%3D1.5.0-green)

I've got my view but I would be glad to get your.

Best

**Comment by hyperupcall** [comment]
As a user of the extension, I I don't have a strong preference, but I would probably prefer the latest version (non-tested) as of today. I haven't really seen any features be deprecated in Bats, and even if this extension is geared towards a particular version of Bats, it will still work with later versions. But again, I don't have a strong preference, just as long as we are pointing towards the repositories that have the most current development activity :P

**Comment by jetmartin** [comment]
Yep, I'll manage that by instinct while I'll gonna review and re-test the all PR merged ;)

**Pull request merged**
